import * as THREE from 'three';
import './style.css';

const CONFIG = { lanes: [-2.5, 0, 2.5], speed: 8.4, levelSeconds: 30, finishDistance: 235, rewindSeconds: 2.5, laneChangeSeconds: .18, jumpSeconds: .78, jumpHeight: 2.142, slideSeconds: .756, invulnerabilitySeconds: 1.2, swipeThreshold: 32 };
const COLORS = { grass: 0x70b85b, path: 0xb8a57b, red: 0xe94560, navy: 0x19324b, cream: 0xfff3d6, blonde: 0xf0bb53, brownHair: 0x5a321f, darkBrown: 0x4a2d22, blue: 0x416c9f, strawberry: 0xe94560, leaf: 0x3e8f4e, wood: 0x765135, white: 0xf6f1e8, sun: 0xffd36b, cloud: 0xf9fbf1, eye: 0x243449 };
const CHARACTERS = [
  { id: 'character-1', label: 'Character 1', skin: 0xffd5b5, hair: COLORS.blonde, style: 'long' },
  { id: 'character-2', label: 'Character 2', skin: 0xc58f69, hair: COLORS.brownHair, style: 'curly' }
];
const LEVELS = [
  { name: 'Sunny park', theme: 'day', collectible: 'strawberry', obstacles: [['bench', 1, 20, 'jump'], ['bike', -1, 38, 'block'], ['sign', 0, 56, 'slide'], ['bench', 1, 74, 'jump'], ['bike', 1, 92, 'block'], ['sign', -1, 110, 'slide'], ['bench', 0, 128, 'jump'], ['bike', -1, 145, 'block'], ['sign', 1, 162, 'slide'], ['bench', -1, 178, 'jump'], ['bike', 0, 195, 'block'], ['sign', -1, 214, 'slide']], collectibles: [['strawberry', 0, 12, 'berry-1'], ['strawberry', 1, 30, 'berry-2'], ['strawberry', -1, 47, 'berry-3'], ['strawberry', 0, 68, 'berry-4'], ['strawberry', 1, 84, 'berry-5'], ['strawberry', -1, 101, 'berry-6'], ['strawberry', 0, 119, 'berry-7'], ['strawberry', 1, 139, 'berry-8'], ['strawberry', -1, 155, 'berry-9'], ['strawberry', 0, 173, 'berry-10'], ['strawberry', 1, 188, 'berry-11'], ['strawberry', -1, 205, 'berry-12'], ['strawberry', 0, 224, 'berry-13']] },
  { name: 'Night park', theme: 'night', collectible: 'cake', obstacles: [['bench', -1, 19, 'jump'], ['car', 1, 36, 'block'], ['sign', 0, 54, 'slide'], ['bike', -1, 70, 'block'], ['bench', 1, 88, 'jump'], ['car', 0, 106, 'block'], ['sign', 1, 124, 'slide'], ['bench', -1, 143, 'jump'], ['car', 1, 161, 'block'], ['sign', -1, 179, 'slide'], ['bike', 0, 198, 'block'], ['car', -1, 216, 'block']], collectibles: [['cake', 1, 11, 'cake-1'], ['cake', -1, 28, 'cake-2'], ['cake', 0, 45, 'cake-3'], ['cake', 1, 63, 'cake-4'], ['cake', -1, 81, 'cake-5'], ['cake', 0, 99, 'cake-6'], ['cake', 1, 117, 'cake-7'], ['cake', -1, 136, 'cake-8'], ['cake', 0, 154, 'cake-9'], ['cake', 1, 173, 'cake-10'], ['cake', -1, 191, 'cake-11'], ['cake', 0, 210, 'cake-12'], ['cake', 1, 226, 'cake-13']] },
  { name: 'Snowy park', theme: 'snow', collectible: 'icecream', obstacles: [['snowbank', 0, 20, 'jump'], ['snowman', -1, 38, 'block'], ['bench', 1, 56, 'jump'], ['snowman', 0, 74, 'block'], ['sign', -1, 92, 'slide'], ['snowbank', 1, 110, 'jump'], ['snowman', -1, 128, 'block'], ['bench', 0, 146, 'jump'], ['sign', 1, 164, 'slide'], ['snowbank', -1, 182, 'jump'], ['snowman', 1, 200, 'block'], ['sign', 0, 218, 'slide']], collectibles: [['icecream', -1, 12, 'ice-1'], ['icecream', 0, 30, 'ice-2'], ['icecream', 1, 47, 'ice-3'], ['icecream', -1, 66, 'ice-4'], ['icecream', 0, 84, 'ice-5'], ['icecream', 1, 102, 'ice-6'], ['icecream', -1, 120, 'ice-7'], ['icecream', 0, 138, 'ice-8'], ['icecream', 1, 156, 'ice-9'], ['icecream', -1, 175, 'ice-10'], ['icecream', 0, 193, 'ice-11'], ['icecream', 1, 211, 'ice-12'], ['icecream', 0, 227, 'ice-13']] },
  { name: 'Rainy city park', theme: 'rain', collectible: 'cupcake', obstacles: [['car', -1, 19, 'block'], ['barrier', 1, 37, 'slide'], ['truck', 0, 55, 'block'], ['box', -1, 73, 'jump'], ['car', 1, 91, 'block'], ['barrier', 0, 109, 'slide'], ['truck', -1, 127, 'block'], ['box', 1, 145, 'jump'], ['car', 0, 163, 'block'], ['barrier', -1, 181, 'slide'], ['truck', 1, 199, 'block'], ['box', 0, 217, 'jump']], collectibles: [['cupcake', 0, 12, 'cup-1'], ['cupcake', 1, 29, 'cup-2'], ['cupcake', -1, 46, 'cup-3'], ['cupcake', 0, 64, 'cup-4'], ['cupcake', 1, 82, 'cup-5'], ['cupcake', -1, 100, 'cup-6'], ['cupcake', 0, 118, 'cup-7'], ['cupcake', 1, 136, 'cup-8'], ['cupcake', -1, 154, 'cup-9'], ['cupcake', 0, 172, 'cup-10'], ['cupcake', 1, 190, 'cup-11'], ['cupcake', -1, 208, 'cup-12'], ['cupcake', 0, 226, 'cup-13']] },
  { name: 'Festival park', theme: 'festival', collectible: 'treat', obstacles: [['box', 1, 19, 'jump'], ['cart', -1, 37, 'block'], ['sign', 0, 55, 'slide'], ['truck', 1, 73, 'block'], ['box', -1, 91, 'jump'], ['cart', 0, 109, 'block'], ['sign', -1, 127, 'slide'], ['truck', 1, 145, 'block'], ['box', 0, 163, 'jump'], ['cart', -1, 181, 'block'], ['sign', 1, 199, 'slide'], ['truck', 0, 217, 'block']], collectibles: [['cake', -1, 12, 'treat-1'], ['icecream', 0, 30, 'treat-2'], ['cupcake', 1, 48, 'treat-3'], ['strawberry', -1, 66, 'treat-4'], ['cake', 0, 84, 'treat-5'], ['icecream', 1, 102, 'treat-6'], ['cupcake', -1, 120, 'treat-7'], ['strawberry', 0, 138, 'treat-8'], ['cake', 1, 156, 'treat-9'], ['icecream', -1, 174, 'treat-10'], ['cupcake', 0, 192, 'treat-11'], ['strawberry', 1, 210, 'treat-12'], ['cake', 0, 227, 'treat-13']] }
];
const THEMES = { day: { sky: 0x9bd5e7, fog: 0x9bd5e7, ground: COLORS.grass, path: COLORS.path, tree: COLORS.leaf, hemi: 0xccecff, sun: 0xfff1ca, power: 2.6 }, night: { sky: 0x101d3b, fog: 0x101d3b, ground: 0x244d47, path: 0x56536d, tree: 0x245746, hemi: 0x788ac7, sun: 0xb7c7ff, power: .9 }, snow: { sky: 0x9fc8e2, fog: 0xd5e9f2, ground: 0xdcebf0, path: 0xbed1d7, tree: 0x527c78, hemi: 0xd6f0ff, sun: 0xf1f6ff, power: 1.5 }, rain: { sky: 0x607b91, fog: 0x607b91, ground: 0x426457, path: 0x56616b, tree: 0x35614e, hemi: 0xb6c8d4, sun: 0xc7d8e2, power: 1.2 }, festival: { sky: 0x7dc4d3, fog: 0x7dc4d3, ground: 0x62a85c, path: 0xb99a80, tree: 0x3e8f4e, hemi: 0xffe4ca, sun: 0xffd36b, power: 2.4 } };
const toSpecs = (rows, collectibles = false) => rows.map(([type, lane, distance, idOrBehavior]) => collectibles ? { type, lane, distance, id: idOrBehavior } : { type, lane, distance, behavior: idOrBehavior });
LEVELS.forEach(level => { level.obstacles = toSpecs(level.obstacles); level.collectibles = toSpecs(level.collectibles, true); });

const canvas = document.querySelector('#game-canvas'); const renderer = new THREE.WebGLRenderer({ canvas, antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.6)); renderer.shadowMap.enabled = true; const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(52, 1, .1, 180); camera.position.set(0, 7.6, 11.5); const clock = new THREE.Clock(); const world = new THREE.Group(); const skyDecor = new THREE.Group(); scene.add(world, skyDecor); const hemiLight = new THREE.HemisphereLight(0xccecff, 0x56713f, 2.1); const sunLight = new THREE.DirectionalLight(0xfff1ca, 2.6); sunLight.position.set(-8, 16, 10); sunLight.castShadow = true; scene.add(hemiLight, sunLight);
const ui = { menuScreen: document.getElementById('menu-screen'), resultScreen: document.getElementById('result-screen'), hud: document.getElementById('hud'), pauseScreen: document.getElementById('pause-screen'), controls: document.getElementById('controls'), hearts: document.getElementById('hearts'), score: document.getElementById('score'), collectibleLabel: document.getElementById('collectible-label'), timer: document.getElementById('timer'), resultEyebrow: document.getElementById('result-eyebrow'), resultTitle: document.getElementById('result-title'), resultCopy: document.getElementById('result-copy'), levelMap: document.getElementById('level-map'), characterMap: document.getElementById('character-map'), startButton: document.getElementById('start-button'), nextButton: document.getElementById('next-button'), resultButton: document.getElementById('result-button'), pauseButton: document.getElementById('pause-button'), resumeButton: document.getElementById('resume-button'), restartButton: document.getElementById('restart-button') };
let mode = 'menu', selectedLevel = 0, selectedCharacter = 0, currentLevel = LEVELS[0], elapsed = 0, lives = 3, score = 0, lane = 1, targetLane = 1, action = null, actionTime = 0, invulnerable = 0, lastTime = 0, collected = new Set(), swipeStart = null, weather = null, finishLine = null; const obstacleMeshes = new Map(); const collectibleMeshes = new Map(); const treeMeshes = [];
function mat(color, roughness = .8) { return new THREE.MeshStandardMaterial({ color, roughness }); } function box(name, size, color, position) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(...size), mat(color)); mesh.name = name; mesh.position.set(...position); mesh.castShadow = true; mesh.receiveShadow = true; return mesh; } function laneX(value) { return CONFIG.lanes[value + 1]; }
function makeHair(girl, character) {
  const cap = new THREE.Mesh(new THREE.SphereGeometry(.54, 24, 18, 0, Math.PI * 2, 0, Math.PI * .68), mat(character.hair));
  cap.position.set(0, 3.35, -.03); girl.add(cap);
  const rearVolume = new THREE.Mesh(new THREE.SphereGeometry(.58, 24, 18), mat(character.hair));
  rearVolume.position.set(0, 3.25, .18); rearVolume.scale.set(1.08, 1.08, .7); girl.add(rearVolume);
  if (character.style === 'long') {
    girl.add(box('long hair back', [.94, 1.42, .3], character.hair, [0, 2.92, .25]));
    [-.42, .42].forEach(x => girl.add(box('long hair side', [.22, 1.12, .3], character.hair, [x, 2.96, .03])));
  } else {
    [[-.48, 3.56, .02], [.48, 3.56, .02], [-.56, 3.24, .05], [.56, 3.24, .05], [-.4, 2.99, .2], [.4, 2.99, .2], [-.25, 2.78, .24], [.25, 2.78, .24], [0, 2.72, .26]].forEach(([x, y, z]) => {
      const curl = new THREE.Mesh(new THREE.SphereGeometry(.3, 18, 14), mat(character.hair)); curl.position.set(x, y, z); girl.add(curl);
    });
  }
}
function makeGirl(character) {
  const girl = new THREE.Group(); girl.name = 'protagonist';
  girl.add(box('red sweater', [.95, 1.0, .58], COLORS.red, [0, 2.15, 0]));
  girl.add(box('white shirt collar', [.38, .12, .58], COLORS.white, [0, 2.66, -.02]));
  girl.add(box('blue tie knot', [.17, .1, .06], COLORS.blue, [0, 2.58, -.34]), box('blue necktie', [.13, .3, .05], COLORS.blue, [0, 2.43, -.34]));
  girl.add(box('navy skirt', [1.14, .9, .72], COLORS.navy, [0, 1.4, 0]));
  [-.39, -.13, .13, .39].forEach(x => girl.add(box('skirt pleat', [.035, .84, .74], 0x314d73, [x, 1.4, -.38])));
  const crest = new THREE.Mesh(new THREE.CircleGeometry(.13, 6), mat(COLORS.red)); crest.position.set(.43, 1.2, -.38); girl.add(crest);
  [-.25, .25].forEach(x => { girl.add(box('leg', [.17, .62, .18], character.skin, [x, .66, 0]), box('red knee sock', [.34, .55, .34], COLORS.red, [x, .32, 0]), box('dark brown shoe', [.36, .16, .58], COLORS.darkBrown, [x, .08, -.1])); });
  const head = new THREE.Mesh(new THREE.SphereGeometry(.48, 20, 16), mat(character.skin)); head.position.set(0, 3.28, 0); girl.add(head); makeHair(girl, character);
  [-.15, .15].forEach(x => { const eye = new THREE.Mesh(new THREE.SphereGeometry(.055, 10, 8), mat(COLORS.eye)); eye.position.set(x, 3.31, -.45); girl.add(eye); });
  const armL = box('left sweater sleeve', [.18, .78, .2], COLORS.red, [-.58, 2.15, 0]); const armR = armL.clone(); armR.name = 'right sweater sleeve'; armR.position.x = .58; girl.add(armL, armR);
  return girl;
}
let girl = makeGirl(CHARACTERS[selectedCharacter]);
function disposeObject(object) { object.traverse(child => { if (child.geometry) child.geometry.dispose(); if (child.material) { const materials = Array.isArray(child.material) ? child.material : [child.material]; materials.forEach(material => material.dispose()); } }); }
function clearLevel() { world.children.slice().forEach(child => { if (child !== girl) { world.remove(child); disposeObject(child); } }); skyDecor.children.slice().forEach(child => { skyDecor.remove(child); disposeObject(child); }); obstacleMeshes.clear(); collectibleMeshes.clear(); treeMeshes.length = 0; weather = null; finishLine = null; if (!world.children.includes(girl)) world.add(girl); }
function makePark(level) { const theme = THEMES[level.theme]; world.add(box('grass', [100, .3, 280], theme.ground, [0, -.55, -105]), box('running path', [9, .08, 280], theme.path, [0, -.38, -105])); [-1, 1].forEach(side => world.add(box('path edge', [.18, .18, 280], COLORS.cream, [side * 4.6, -.29, -105]))); for (let z = -8; z > -270; z -= 18) [-1, 1].forEach(side => { const tree = new THREE.Group(); tree.add(box('tree trunk', [.7, 4.2, .7], COLORS.wood, [0, 1.55, 0])); const crown = new THREE.Mesh(new THREE.DodecahedronGeometry(2.4, 0), mat(theme.tree)); crown.position.y = 5.3; tree.add(crown); if (level.theme === 'snow') tree.add(new THREE.Mesh(new THREE.SphereGeometry(2.5, 8, 6), mat(0xf6fbff))); tree.position.set(side * 10, 0, z); world.add(tree); treeMeshes.push({ tree, baseZ: z }); }); finishLine = new THREE.Group(); finishLine.name = 'finish line'; finishLine.add(box('finish line', [9, .05, 1.2], COLORS.white, [0, -.3, 0])); for (let i = -4; i < 5; i++) finishLine.add(box('finish tile', [1, .06, 1.2], i % 2 ? COLORS.navy : COLORS.white, [i, -.25, 0])); world.add(finishLine); if (level.theme === 'festival') [-1, 1].forEach(x => world.add(box('festival banner', [1.8, .8, .08], x < 0 ? 0xffd36b : 0x6f8ff0, [x * 5.8, 4, -35]))); }
function makeSkyDecor(theme) { if (theme === 'night') { const moon = new THREE.Mesh(new THREE.SphereGeometry(2.3, 16, 12), new THREE.MeshBasicMaterial({ color: 0xfff1bd })); moon.position.set(-16, 15, -66); skyDecor.add(moon); } else { const sun = new THREE.Mesh(new THREE.SphereGeometry(3.2, 12, 8), new THREE.MeshBasicMaterial({ color: theme === 'snow' ? 0xf5fbff : COLORS.sun })); sun.position.set(-18, 14, -62); skyDecor.add(sun); } }
function makeWeather(theme) { if (theme !== 'snow' && theme !== 'rain') return; const count = 180; const positions = new Float32Array(count * 3); for (let i = 0; i < count; i++) { positions[i * 3] = (Math.random() - .5) * 28; positions[i * 3 + 1] = Math.random() * 13; positions[i * 3 + 2] = -Math.random() * 250; } const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3)); const points = new THREE.Points(geometry, new THREE.PointsMaterial({ color: theme === 'snow' ? 0xffffff : 0xb9d9e7, size: theme === 'snow' ? .16 : .08, transparent: true, opacity: .75 })); world.add(points); weather = { points, snow: theme === 'snow' }; }
function makeObstacle(spec, index) { const g = new THREE.Group(); g.position.x = laneX(spec.lane); const color = spec.type === 'truck' ? 0x365f79 : spec.type === 'car' ? 0xd94c54 : spec.type === 'box' ? 0xb7784c : spec.type === 'cart' ? 0x9a5fbd : COLORS.wood; if (spec.type === 'bench') { g.add(box('bench seat', [2.2, .28, .65], color, [0, .5, 0])); [-.7, .7].forEach(x => g.add(box('bench leg', [.18, .55, .5], color, [x, .15, 0]))); } if (spec.type === 'sign') { [-.74, .74].forEach(x => g.add(box('sign leg', [.18, 3, .18], color, [x, 1.5, 0]))); g.add(box('sign board', [2.1, .85, .16], 0xe94560, [0, 3.4, 0])); } if (spec.type === 'bike') { g.add(box('bike body', [1.2, .2, .2], COLORS.red, [0, .75, 0]), box('bike rider', [.42, 2.1, .42], COLORS.navy, [0, 1.75, 0])); [-.45, .45].forEach(x => { const wheel = new THREE.Mesh(new THREE.TorusGeometry(.4, .07, 8, 16), mat(COLORS.navy)); wheel.rotation.y = Math.PI / 2; wheel.position.set(x, .45, 0); g.add(wheel); }); } if (spec.type === 'car' || spec.type === 'truck') { const big = spec.type === 'truck'; g.add(box('vehicle body', [big ? 1.8 : 1.55, .75, 2.2], color, [0, .65, 0]), box('vehicle window', [big ? 1.35 : 1.1, .45, .08], 0x9fd0dc, [0, 1.1, -.85])); } if (spec.type === 'snowbank') g.add(new THREE.Mesh(new THREE.SphereGeometry(1.15, 12, 8), mat(0xf8fcff))); if (spec.type === 'snowman') { const body = new THREE.Mesh(new THREE.SphereGeometry(.9, 12, 8), mat(0xf8fcff)); const head = new THREE.Mesh(new THREE.SphereGeometry(.55, 12, 8), mat(0xf8fcff)); body.position.y = .9; head.position.y = 1.95; g.add(body, head); } if (spec.type === 'box') g.add(box('crate', [1.45, 1.2, 1.3], color, [0, .6, 0])); if (spec.type === 'barrier') g.add(box('barrier', [2.1, .9, .25], 0xffc04d, [0, .8, 0])); if (spec.type === 'cart') g.add(box('market cart', [1.8, 1.1, 1.1], color, [0, .6, 0]), box('cart roof', [2, .15, 1.25], 0xffd36b, [0, 1.35, 0])); g.name = `obstacle-${selectedLevel}-${index}`; g.traverse(o => { if (o.isMesh) { o.castShadow = true; o.receiveShadow = true; } }); world.add(g); obstacleMeshes.set(g.name, g); }
function makeCollectible(spec) { const g = new THREE.Group(); g.position.x = laneX(spec.lane); if (spec.type === 'strawberry') g.add(new THREE.Mesh(new THREE.SphereGeometry(.5, 12, 8), mat(COLORS.strawberry)), box('leaf', [.16, .36, .16], COLORS.leaf, [0, .5, 0])); else if (spec.type === 'icecream') { const cone = new THREE.Mesh(new THREE.ConeGeometry(.3, .7, 10), mat(0xd79455)); const scoop = new THREE.Mesh(new THREE.SphereGeometry(.42, 12, 8), mat(0xff9bba)); cone.position.y = .35; scoop.position.y = .85; g.add(cone, scoop); } else { g.add(box('treat base', [.75, .55, .75], spec.type === 'cupcake' ? 0xb86a56 : 0xd58c62, [0, .45, 0]), new THREE.Mesh(new THREE.SphereGeometry(.5, 12, 8), mat(spec.type === 'cake' ? 0xff9db5 : 0xff8d9f))); g.children[1].position.y = .85; } g.name = spec.id; g.traverse(o => { if (o.isMesh) o.castShadow = true; }); world.add(g); collectibleMeshes.set(spec.id, g); }
function resetLevel() { elapsed = 0; lives = 3; score = 0; lane = 1; targetLane = 1; action = null; actionTime = 0; invulnerable = 0; collected.clear(); girl.position.set(0, 0, 0); girl.scale.set(1, 1, 1); updateHUD(); }
function loadLevel(index) { selectedLevel = index; currentLevel = LEVELS[index]; clearLevel(); const theme = THEMES[currentLevel.theme]; scene.background = new THREE.Color(theme.sky); scene.fog = new THREE.Fog(theme.fog, 42, 120); hemiLight.color.setHex(theme.hemi); hemiLight.intensity = currentLevel.theme === 'night' ? 1.3 : 2.1; sunLight.color.setHex(theme.sun); sunLight.intensity = theme.power; makePark(currentLevel); makeSkyDecor(currentLevel.theme); makeWeather(currentLevel.theme); currentLevel.obstacles.forEach(makeObstacle); currentLevel.collectibles.forEach(makeCollectible); resetLevel(); updateMap(); }
function updateMap() { [...ui.levelMap.children].forEach((button, index) => { button.classList.toggle('selected', index === selectedLevel); button.setAttribute('aria-pressed', index === selectedLevel); }); ui.startButton.textContent = `Start ${currentLevel.name}`; }
function updateCharacterMap() { [...ui.characterMap.children].forEach((button, index) => { button.classList.toggle('selected', index === selectedCharacter); button.setAttribute('aria-pressed', index === selectedCharacter); }); }
function selectCharacter(index) { if (index === selectedCharacter) return; if (world.children.includes(girl)) world.remove(girl); disposeObject(girl); selectedCharacter = index; girl = makeGirl(CHARACTERS[selectedCharacter]); world.add(girl); resetLevel(); updateCharacterMap(); }
function setMode(next) { mode = next; ui.menuScreen.classList.toggle('hidden', next !== 'menu'); ui.resultScreen.classList.toggle('hidden', !['success', 'gameover'].includes(next)); ui.hud.classList.toggle('hidden', next !== 'playing'); ui.controls.classList.toggle('hidden', next !== 'playing'); ui.pauseScreen.classList.toggle('hidden', next !== 'paused'); }
function startGame() { loadLevel(selectedLevel); setMode('playing'); } function showResult(success) { setMode(success ? 'success' : 'gameover'); ui.resultEyebrow.textContent = success ? 'LEVEL COMPLETE' : 'RUN OVER'; ui.resultTitle.textContent = success ? 'You made it!' : 'Keep practicing'; ui.resultCopy.textContent = `${currentLevel.name} · Treats collected: ${score}`; ui.nextButton.classList.toggle('hidden', !success || selectedLevel >= LEVELS.length - 1); ui.resultButton.textContent = 'Back to map'; }
function updateHUD() { ui.hearts.textContent = `${'♥ '.repeat(lives)}${'♡ '.repeat(3 - lives)}`.trim(); ui.score.textContent = score; ui.collectibleLabel.textContent = currentLevel.collectible === 'strawberry' ? 'Berries' : 'Treats'; ui.timer.textContent = Math.max(0, Math.ceil(CONFIG.levelSeconds - elapsed)); }
function doAction(input) { if (mode !== 'playing') return; if (input === 'left' || input === 'right') { if (action) return; const next = targetLane + (input === 'left' ? -1 : 1); if (next >= 0 && next <= 2) targetLane = next; return; } if (action) return; if (input === 'up') action = 'jump'; if (input === 'down') action = 'slide'; if (action) actionTime = 0; }
function speedMultiplier() { return Math.pow(1.1, selectedLevel); } function currentZ(distance) { return -(distance - elapsed * CONFIG.speed * speedMultiplier()); } function obstacleHalfWidth(spec) { return ['bench', 'sign', 'barrier'].includes(spec.type) ? 1.05 : .72; } function isSafe(spec) { const overlaps = Math.abs(girl.position.x - laneX(spec.lane)) < .525 + obstacleHalfWidth(spec); if (!overlaps) return true; if (spec.behavior === 'jump') return action === 'jump' && girl.position.y > .292; if (spec.behavior === 'slide') return action === 'slide'; return false; } function handleCollision(spec) { if (invulnerable > 0 || isSafe(spec)) return; lives -= 1; invulnerable = CONFIG.invulnerabilitySeconds; elapsed = Math.max(0, elapsed - CONFIG.rewindSeconds); updateHUD(); if (lives <= 0) showResult(false); }
function updateGame(dt) { elapsed += dt; invulnerable = Math.max(0, invulnerable - dt); if (targetLane !== lane) { const direction = Math.sign(targetLane - lane); const targetX = CONFIG.lanes[targetLane]; const laneSpeed = Math.abs(CONFIG.lanes[1] - CONFIG.lanes[0]) / CONFIG.laneChangeSeconds; girl.position.x += direction * laneSpeed * dt; if ((direction > 0 && girl.position.x >= targetX) || (direction < 0 && girl.position.x <= targetX)) { girl.position.x = targetX; lane = targetLane; } } const levelSpeed = CONFIG.speed * speedMultiplier(); treeMeshes.forEach(({ tree, baseZ }) => { tree.position.z = ((baseZ + elapsed * levelSpeed + 260) % 280) - 260; }); if (finishLine) finishLine.position.z = currentZ(CONFIG.finishDistance); if (weather) { const positions = weather.points.geometry.attributes.position.array; for (let i = 0; i < positions.length; i += 3) { positions[i + 1] -= dt * (weather.snow ? 2.2 : 7); if (positions[i + 1] < 0) positions[i + 1] = 13; } weather.points.geometry.attributes.position.needsUpdate = true; } if (action) { actionTime += dt; const duration = action === 'jump' ? CONFIG.jumpSeconds : CONFIG.slideSeconds; const progress = actionTime / duration; girl.position.y = action === 'jump' ? Math.sin(Math.min(progress, 1) * Math.PI) * CONFIG.jumpHeight : .02; if (actionTime >= duration) { action = null; actionTime = 0; girl.position.y = 0; } } girl.scale.y = action === 'slide' ? .62 : 1; girl.rotation.z = Math.sin(elapsed * 18) * .025; if (!action) girl.position.y = Math.abs(Math.sin(elapsed * 16)) * .05; currentLevel.obstacles.forEach((spec, index) => { const mesh = obstacleMeshes.get(`obstacle-${selectedLevel}-${index}`); mesh.position.z = currentZ(spec.distance); if (Math.abs(mesh.position.z) < 1) handleCollision(spec); }); currentLevel.collectibles.forEach(spec => { const collectible = collectibleMeshes.get(spec.id); collectible.position.z = currentZ(spec.distance); collectible.visible = !collected.has(spec.id); if (!collected.has(spec.id) && Math.abs(collectible.position.z) < .9 && Math.abs(girl.position.x - laneX(spec.lane)) < .8) { collected.add(spec.id); score += 1; updateHUD(); } }); if (elapsed >= CONFIG.levelSeconds || finishLine?.position.z >= 0) showResult(true); updateHUD(); }
function resize() { const w = innerWidth, h = innerHeight; renderer.setSize(w, h, false); camera.aspect = w / h; camera.updateProjectionMatrix(); } function animate() { requestAnimationFrame(animate); const now = clock.getElapsedTime(); const dt = Math.min(.05, now - lastTime || 0); lastTime = now; if (mode === 'playing') updateGame(dt); camera.lookAt(0, 1.7, -10); renderer.render(scene, camera); }
document.addEventListener('keydown', event => { const map = { a: 'left', ArrowLeft: 'left', d: 'right', ArrowRight: 'right', w: 'up', ArrowUp: 'up', s: 'down', ArrowDown: 'down' }; if (map[event.key]) { event.preventDefault(); doAction(map[event.key]); } if (event.key === 'Escape' && mode === 'playing') setMode('paused'); }); document.addEventListener('pointerdown', event => { if (event.isPrimary && event.pointerType !== 'mouse') swipeStart = { x: event.clientX, y: event.clientY }; }); document.addEventListener('pointerup', event => { if (!swipeStart || !event.isPrimary) return; const dx = event.clientX - swipeStart.x; const dy = event.clientY - swipeStart.y; swipeStart = null; if (Math.max(Math.abs(dx), Math.abs(dy)) < CONFIG.swipeThreshold) return; doAction(Math.abs(dx) > Math.abs(dy) ? (dx < 0 ? 'left' : 'right') : (dy < 0 ? 'up' : 'down')); }); document.addEventListener('pointercancel', () => { swipeStart = null; }); document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('pointerdown', event => { event.preventDefault(); doAction(button.dataset.action); }));
CHARACTERS.forEach((character, index) => { const button = document.createElement('button'); button.className = 'character-node'; button.type = 'button'; button.setAttribute('aria-label', character.label); button.innerHTML = `<img class="character-preview" src="/characters/${character.id}.png" alt=""><strong>${character.label}</strong>`; button.addEventListener('click', () => selectCharacter(index)); ui.characterMap.appendChild(button); }); LEVELS.forEach((level, index) => { const button = document.createElement('button'); button.className = 'level-node'; button.type = 'button'; button.innerHTML = `<span>LEVEL ${index + 1}</span><strong>${level.name}</strong>`; button.addEventListener('click', () => { selectedLevel = index; loadLevel(index); setMode('menu'); }); ui.levelMap.appendChild(button); }); ui.startButton.addEventListener('click', startGame); ui.resultButton.addEventListener('click', () => setMode('menu')); ui.nextButton.addEventListener('click', () => { selectedLevel = Math.min(selectedLevel + 1, LEVELS.length - 1); startGame(); }); ui.pauseButton.addEventListener('click', () => setMode('paused')); ui.resumeButton.addEventListener('click', () => setMode('playing')); ui.restartButton.addEventListener('click', startGame); addEventListener('resize', resize); loadLevel(0); updateMap(); updateCharacterMap(); resize(); setMode('menu'); animate();
